### ISSUE TITLE
ImageView from Usage section reports error

### ISSUE THREAD

**Issue by nnorris7** [kean/FetchImage#1]
I'm trying to use FetchImage and copied the ImageView code supplied in the Safe section into a new SwiftUI file. Unfortunately when I do that, I receive the following error pointing at 'static var previews: some View {' :

Function declares an opaque return type, but has no return statements in its body from which to infer an underlying type

I can resolve this error by adding the keyword 'return' in front of the ImageView statement below but when attempting to preview, only a small grey square/box shows up, not the image.

Any suggestions?
![Screen Shot 2020-03-22 at 12 17 44 PM](https://user-images.githubusercontent.com/1887437/77258353-55667300-6c37-11ea-9637-802aaedb7d36.png)

**Comment by kean** [comment]
Hey, can you share the entire sample that is not compiling please?

**Comment by nnorris7** [comment]
I added a SwiftUI View to my project and pasted the below code in. This compiles now but doesn't display the correct image, just the grey box above.


import SwiftUI
import FetchImage

public struct ImageView: View {
    @ObservedObject var image: FetchImage

    public var body: some View {
        ZStack {
            Rectangle().fill(Color.gray)
            image.view?
                .resizable()
                .aspectRatio(contentMode: .fill)
        }

        // (Optional) Animate image appearance
        .animation(.default)

        // (Optional) Cancel and restart requests during scrolling
        .onAppear(perform: image.fetch)
        .onDisappear(perform: image.cancel)
    }
}

struct ImageView_Previews: PreviewProvider {
    static var previews: some View {
        let url = URL(string: "https://cloud.githubusercontent.com/assets/1567433/9781817/ecb16e82-57a0-11e5-9b43-6b4f52659997.jpg")!
        return ImageView(image: FetchImage(url: url, pipeline: .shared))
            .aspectRatio(contentMode: .fit)
            .frame(width: 80, height: 80)
            .clipped()
    }
}

**Comment by kean** [comment]
Hmm, it seems to work fine on my machine.

**Comment by nnorris7** [comment]
Sorry, if I click the Live Preview button, the grey box is replaced with the real image. In past, images have loaded after clicking Resume on the main preview canvas.

I wanted to use this view in a List. How do you call it to pass in the required URL?

**Comment by kean** [comment]
Just like it is shown in the example.

```swift
FetchImage(url: "https://cloud.githubusercontent.com/assets/1567433/9781817/ecb16e82-57a0-11e5-9b43-6b4f52659997.jpg")!)
```

When to create `FetchImage` and how to pass it to a view is completely up to you. You could use `@ObservableObject`, or `@State`. I would suggest going through [this post](https://kean.github.io/post/swiftui-data-flow.) if you have questions regarding these propery wrappers.

**Comment by nnorris7** [comment]
The link pointed to by  "this post" in your comment above it broken, goes to a 404 page.
![Screen Shot 2020-03-23 at 10 44 35 AM](https://user-images.githubusercontent.com/1887437/77346342-53fa8080-6cf3-11ea-85dd-0fdbff41b5b8.png)

**Comment by kean** [comment]
My bad, put dot in the wrong place. https://kean.github.io/post/swiftui-data-flow
