### ISSUE TITLE
How to use with optional URLs?

### ISSUE THREAD

**Issue by reubits** [kean/FetchImage#12]
How can we use `FetchImage` to optionally show images when the url may or may not be nil? I need the `FetchImage` instance to conform to `ObservedObject` so it can't be optional, but there seems to be no way to allow for an "empty" FetchImage.

**Comment by vmartinelli** [comment]
Hello. When using a custom SwiftUI View together with `FetchImage` the code may be something like this:
```swift
someOptionalURL.map { FetchImageView(url: $0) } 
```

The `FetchImageView` above has the code:

```swift
public struct FetchImageView: View {
    @StateObject private var fetchImage: FetchImage

    public init(url: URL) {
        let request = ImageRequest(url: url)
        self._fetchImage = .init(wrappedValue: .init(request: request))
        
        // ...
    }

    // body implementation
}

```

The rest of the implementation looks like the `ImageView` code at the end of `FetchImage` docs.

I hope this can help! ;)

**Comment by kean** [comment]
Thanks, @vmartinelli, this looks pretty good.

I'm also in the middle of redesigning to support StateObject (and incidentally optional URLs): https://github.com/kean/FetchImage/pull/14

**Comment by kean** [comment]
With [FetchImage 0.4.0]()

```
struct ImageView: View {
    let url: URL?

    @StateObject private var image = FetchImage()

    var body: some View {
        ZStack {
            Rectangle().fill(Color.gray)
            image.view?
                .resizable()
                .aspectRatio(contentMode: .fill)
                .clipped()
        }
        .onAppear { url.map(image.load) }
        .onDisappear(perform: image.reset)
    }
}
```
