### ISSUE TITLE
Image disappears on refresh

### ISSUE THREAD

**Issue by joshuazmiller** [kean/FetchImage#13]
I followed the example in the Readme. Using the library usually works correctly, but something goes wrong when the image is refreshed.

Hard to describe without code so here's some:

### RemoteImage struct implementing FetchImage like the example in the Readme
Note, also tried the other onAppear/onDisappear which cancels the request onDisappear but same problem.
```
import SwiftUI

import FetchImage

struct RemoteImage: View {
    @ObservedObject var image: FetchImage

    public var body: some View {
        ZStack {
            Rectangle().fill(Color.gray)
            image.view?
                .resizable()
                .aspectRatio(contentMode: .fill)
        }
        .onAppear {
            self.image.priority = .normal
            self.image.fetch() // Restart the request if previous download failed
        }
        .onDisappear {
            self.image.priority = .low
        }
    }
}

```

### Profile struct makes use of RemoteImage
```
struct Profile: View {
    var profile: ProfileDetails

    var body: some View {
        VStack {
            if profile.avatarUrl != nil, let url = URL(string: profile.avatarUrl!)! {
                RemoteImage(image: FetchImage(url: url))
                    .frame(width: 80, height: 80)
                    .cornerRadius(80)
            }
        }
    }
}
```

### Snippet that uses the Profile struct
```
ForEach(profiles, id: \.username) { p in
    Profile(profile: p)
}
```

### Problem occurs 
Problem occurs when the `profiles` variable consumed in the `ForEach` gets refreshed. `profiles` gets refreshed when an additional profile is added or an existing profile is deleted. The problem occurs at that point, and all the images go gray. Navigating away and back to the tab hosting the list reloads the image correctly. But on the reload the image goes gray as described.

Edit: Problem also appears when the image is not in the foreground, like when a dialog is displayed.

Seems that Swift is releasing the reference prematurely or something. I'm not sure what's wrong, based on the articles you've written you are an expert on observables and how SwiftUI operates under the hood, so maybe you have an idea what's going on.

Thanks.

### Notes
Using Xcode 12, iOS 14.4, and MacOS BigSur.

**Comment by kean** [comment]
Hi, if are using `@ObservedObject`, you should own the lifetime of the observable object, in this case, `FetchImage`. SwiftUI gives no guarantees about the object lifetime, it might even get deallocated after `body` calculation.

I would suggest switching to `@StateObject`. There are some examples in https://github.com/kean/FetchImage/issues/7. If you can't use `@StateObject` yet, you should figure out a way to retain `FetchImage` instances in a different way.

**Comment by joshuazmiller** [comment]
Thank you. I appreciate all the work you've done here. I am curious though. I re-implemented using [URLImage](https://github.com/dmytro-anokhin/url-image) which is another open source library while keeping the same code structure that I have now and I am not experiencing the above issues. 

On the surface, I'm not sure if that library is as optimized as yours, but I want to point this out, because it would be interesting to understand why and maybe improve your library, or else understand what the limitations of that library is and where this library sacrifices on this component to achieve better optimization or some other goal. Not to step on any toes here, purely pointing out the other solution since it might help improve this one.

I'm open to trying out this solution again if you do decide to make changes that make it work better inside ForEach loops and provide feedback if that fixes the situation. If you'd like me to remove the link to the competing library feel free to alter or delete this comment and I totally understand. 

🙏

**Comment by kean** [comment]
I set up a test project with the code you provided, and I can't reproduce the issue. If you could provide a sample project where you can repro, that would be helpful.

You can also use [Nuke](https://github.com/kean/Nuke) directly, FetchImage itself barely does anything.

**Comment by kean** [comment]
SwiftUI is so weird. I'm testing with a List, I got 8 items visible at a time. When I open it, I get the following calls:

- onAppear for indexes 0...16
- onDisappear for 8...16

When I refresh the list:

- onAppear for 10...16 (8...9 still in "disappeared" state)

**Comment by kean** [comment]
Please try with [FetchImage 0.4.0](https://github.com/kean/FetchImage/releases/tag/0.4.0) and reopen if you can reproduce the issue.

**Comment by joshuazmiller** [comment]
Hey, thank you! I plan to give it a try sometime this week and let you know how it goes. 🙏

**Comment by joshuazmiller** [comment]
I tested the update and can report back that it works very nicely. 💪 

The caching also appears to perform a lot better than URLImage 🥂 

Only caveat is the lack of iOS 13 support, but can't have everything 🤷 

Thanks! 😄

**Comment by kean** [comment]
> The caching also appears to perform a lot better than URLImage 🥂

I'm stunned 😹

By the way, make sure to enable [aggressive disk cache](https://github.com/kean/Nuke#aggressive-lru-disk-cache) in case you don't need HTTP caching. It's currently disabled by default, but this will change in Nuke 10.

> Only caveat is the lack of iOS 13 support, but can't have everything

It does, but you need to be careful when using `@ObservedObject`
