### ISSUE TITLE
Cache persistence between app opens

### ISSUE THREAD

**Issue by joshuazmiller** [kean/FetchImage#15]
Is there a way to persist certain images between app opens? 

- This would be great to reduce network traffic and make the app feel more instant for remote images that are consistently required (such as a user's avatar)
- This would improve offline or low data situations

**Comment by kean** [comment]
Absolutely, please refer to https://github.com/kean/Nuke#caching

**Comment by joshuazmiller** [comment]
Thanks for the pointer. Just reading into it. 

I modified `onAppear` to look like the following, however it still appears to be loading from the web on each open.
```
.onAppear {
    DataLoader.sharedUrlCache.diskCapacity = 10000000
    DataLoader.sharedUrlCache.memoryCapacity = 10000000
    let request = ImageRequest(url: url)
    image.load(request)
}
```

Do you mind explaining what I need to do to properly activate the disk cache?

(Ideally, I'd like to use disk for only some images, and LRU for others.)

**Comment by kean** [comment]
The default cache (`URLCache`) implements [HTTP caching](https://kean.blog/post/image-caching). If it's not working it means that the server doesn't set proper HTTP headers.

Another option is to use an [aggressive cache](https://github.com/kean/Nuke#aggressive-lru-disk-cache). It ignores HTTP headers. It is also faster than the native `URLCache`. This cache will be enabled by default starting with Nuke 10.

**Comment by joshuazmiller** [comment]
Thank you so much. I'm going to explore aggressive caching. 

Just for others who might end up here. What I did find improved my UX is using Nuke's awesome [Preheating](https://github.com/kean/Nuke#image-preheating) functionality. This helps in the case the user doesn't immediately land on the tab that requires the image.

```
import Nuke
...
class GQL {
    let preheater = ImagePreheater()
    
    func getProfiles() {
        ...
        if let avatarUrl = profile?.avatarUrl, let url = URL(string: avatarUrl) {
            self.preheater.startPreheating(with: [url])
        }
    }
}
```

Also, I'm using Cloud Storage from Firebase as an image server, so I was surprised HTTP Cache was not set, but then I realized I needed to manually set it with the image upload.

For those using Firebase Cloud Storage you can do this like:
```
...
// set the cache to 30 days
let newMetadata = StorageMetadata(dictionary: ["cacheControl": "public,max-age=2592000"])!

// upload - see Cloud Storage documentation for full details (https://firebase.google.com/docs/storage/ios/start)
let uploadTask = imageRef.putData(data, metadata: newMetadata) { metadata, _ in
   ...
}
```
After setting the `cacheControl` things are snappy and image no longer reloads on each open.
