### ISSUE TITLE
How to integrate SVG support?

### ISSUE THREAD

**Issue by basememara** [kean/FetchImage#16]
I understand SVG support is out of scope for Nuke, but asking how can `FetchImage` support custom decoders? Currently I'm using [SwiftSVG](https://github.com/mchoe/SwiftSVG) and doing this somewhere in my app start:

```swift
ImageDecoderRegistry.shared.register { context in
    let isSVG = context.urlResponse?.url?.absoluteString.hasSuffix(".svg") ?? false
    return isSVG ? ImageDecoders.Empty() : nil
}
```

How do I use this in my image view?

```swift
struct ImageView: View {
    let url: URL

    @StateObject private var image = FetchImage()

    var body: some View {
        ZStack {
            Rectangle().fill(Color.gray)
            image.view?
                .resizable()
                .aspectRatio(contentMode: .fill)
                .clipped()
        }
        .onAppear { image.load(url) } // Use SVG decoder here?
        .onDisappear(perform: image.reset)
    }
}
```

It seems some APIs have to be exposed from `FetchImage` to do this, is there a way to do this?

**Comment by kean** [comment]
Yes, it needs to expose `ImageResponse`, not just the resulting image. I haven't added this API yet, but should be an easy change. The response contains image data (for certain decoders such as `ImageDecoders.Empty`). You can use this data to render it as SVG.

**Comment by kean** [comment]
Starting with Nuke 10 (beta coming tomorrow), `FetchImage` is now part of the main repo and it has an image response (`ImageResponse`) property.
