### ISSUE TITLE
Default example in the Readme is confusing when used with changing data

### ISSUE THREAD

**Issue by Bersaelor** [kean/FetchImage#18]
In my tests `onAppear` is only called once for a `View` and is not called again when the `URL` we give it in the initializer changes.
Therefore the example `ImageView` in the demo would only works if you ever only load a static image, not changing images in the same spot.

Example:

```swift
import SwiftUI
import FetchImage

struct ContentView: View {

    private static let images = [
        "https://picsum.photos/id/237/200/300",
        "https://picsum.photos/id/238/200/300",
        "https://picsum.photos/id/239/200/300"
    ]

    @State private var imageNumber: Int = 0

    var body: some View {
        VStack(alignment: .center) {
            Text("Showing image number: \(imageNumber)")
            Button(action: self.forward) {
                Text("Next")
            }
            ImageView(url: URL(string: ContentView.images[imageNumber])!)
                .frame(width: 75, height: 100)
                .padding()
        }
    }

    private func forward() {
        imageNumber = (imageNumber + 1) % ContentView.images.count
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```

![Screen Recording 2021-04-23 at 17 06 12  2021-04-23 17_06_50](https://user-images.githubusercontent.com/4517582/115891380-4e232180-a456-11eb-9c80-9b8968c7a64c.gif)

**Comment by Bersaelor** [comment]
What worked for us was the modify the `ImageView` as follows:

```swift
    var body: some View {
        ZStack {
            Rectangle().fill(Color.gray)
            image.view?
                .resizable()
                .aspectRatio(contentMode: .fill)
                .clipped()
        }
        .onAppear { image.load(url) }
        .onChange(of: url) { newURL in
            image.load(newURL)
        }
        .onDisappear(perform: image.reset)
    }
 ```

**Comment by kean** [comment]
Hey, @Bersaelor. Thanks for the suggestion!

There is a note in README regarding this problem:

> If the URL changes, add .id(url) to your ImageView. This will ensure that onAppear is called when the URL changes.

It looks like your approach is potentially better because it doesn't trigger a view reload.

**Comment by kean** [comment]
I updated the README with your suggestion. Thanks, @Bersaelor!
