### ISSUE TITLE
Could not cast value of type 'CALayer' to 'SwiftUI.MaskLayer'

### ISSUE THREAD

**Issue by JS1010111** [kean/FetchImage#4]
First, congratulations for the Nuke 9 release and thank you for this great package!
I was searching for a better image caching solution and Nuke is looking awesome as I refactor my iOS project to use it.

I'm just stuck with an issue that is breaking my app.

`Could not cast value of type 'CALayer' (0x205890c80) to 'SwiftUI.MaskLayer' (0x204dd1da8).`

It's seems related to the use of `.clipped()` on the view stack and `.cornerRadius()` on an image that is in this stack.

Not sure what is happening yet since I'm not being able to reproduce it with a simpler sample code, but I'll share more info here as soon as I have.

**Comment by JS1010111** [comment]
Well, I have just simplified my view stack and the issue is now gone. Not sure what was causing it... probably some unnecessary complexity on my view stack code.

Anyway, thanks again for this great package! Performance is top notch as well as memory usage and default caching strategy. I hope I can contribute to the project in the future!

**Comment by kean** [comment]
Contributions are welcome!
