### ISSUE TITLE
Rending Mode inside NavigationLink

### ISSUE THREAD

**Issue by weisso5** [kean/FetchImage#6]
In Xcode 12 beta there is some strange behavior with FetchImage and Navigation link:

This is a pretty specific situation and there is a "workaround", but when wrapping the FetchImage view in a Navigation Link using the example, it will just render the Rectangle.

Simplified example:
`NavigationLink {
     ZStack {
            Rectangle().fill(Color.gray)
           fetchImage.view?
                .resizable()
                .aspectRatio(contentMode: .fill)
        }
}`

after messing around, it seems to be related to the Rendering Mode on SwiftUI image View returned in Fetch Image. Rendering Mode is poorly documented. Forcing Original Rendering Mode resolves all the weird behavior, but I wanted to post it because it feels like a hack:

`public extension FetchImage {
    var view: SwiftUI.Image? {
        #if os(macOS)
        return image.map(Image.init(nsImage:))
        #else
        return image.map(Image.init(uiImage:))?.renderingMode(.original)
        #endif
    }
}
`

**Comment by apanagar** [comment]
This is also an issue in Xcode 11 apparently. I have a FetchImage wrapped in a NavigationLink to render grid cells, here's what I get

![image](https://user-images.githubusercontent.com/180389/91238904-f54a9000-e6f2-11ea-844d-39192d4e46bd.png)

and when setting the `rendermode(.oroginal)`

<img  alt="Screen Shot 2020-08-25 at 4 50 25 PM" src="https://user-images.githubusercontent.com/180389/91239152-9cc7c280-e6f3-11ea-99c2-a2481955cbd5.png">

**Comment by kean** [comment]
There seems to be a better way to achieve that. I also tested it in iOS 14.3 and this issue had been fixed as far as I can tell.
