### ISSUE TITLE
Avoid extra rendering.

### ISSUE THREAD

**Issue by oivvio** [kean/FetchImage#8]
I'm having a bit of an issue with FetchImage rendering too many times. I think at least.

I set up the simplest possible project. Just copy-pasted the example code from the FetchImage docs into a fresh SwiftUI project. 

Running that through the Inspector I get a view count of 3 for the ImageView. Is that to be expected?

<img width="791" alt="Screen Shot 2020-11-08 at 23 23 28" src="https://user-images.githubusercontent.com/411220/98485843-97b9e000-2219-11eb-8a5f-89bef121f45a.png">

**Comment by kean** [comment]
Could you please provide an example? SwiftUI re-create views liberally, so it's not unexpected.

**Comment by kean** [comment]
> Running that through the Inspector I get a view count of 3 for the ImageView. Is that to be expected?

This sounds reasonable – progress reports.
