### ISSUE TITLE
Resize ImageProcessor doesn't work.

### ISSUE THREAD

**Issue by Prince2k3** [kean/FetchImage#9]
Hey! Thanks for making this library it is very nice. I ran into a problem trying using the resize processor.  The problem is that It doesn't work.

```swift 
WebImage(request: ImageRequest(url: bannerImageURL, processors: [
             ImageProcessors.Resize(
                  height: 260,
                  unit: .pixels,
                  crop: true,
                  upscale: true
              )
         ]
     )
)
```

```swift 
public struct WebImage: View {
    @ObservedObject var image: FetchImage
    
    public var body: some View {
        VStack {
            image.view?
                .resizable()
                .aspectRatio(contentMode: .fill)
        }
    }
    
    public init(image: FetchImage) {
        self.image = image
    }
    
    public init(_ url: URL) {
        self.image = FetchImage(url: url)
    }
    
    public init(request: ImageRequest) {
        self.image = FetchImage(request: request)
    }
}
```

The output is the image not resized or cropped.  Unless I misunderstood the usage of the processor.

Thanks for the help.

**Comment by kean** [comment]
Hi, yeah `crop` doesn't make sense when you only provide `height` or `width` – the other dimension isn't limited. I'm going to update Nuke to remove this parameter for the given initializer.

Resizing should still work. If the image height is more than 260 pixels, it will be downscales maintaining its aspect ratio.

**Comment by Prince2k3** [comment]
@kean Thanks for replying back and looking into my issue. I should have mention I did try setting different parameters on Resize initializer to get something to happen with the image. Nothing happened and instead I ended up using my own ImageProcessor (by the way, thank you so much for allowing this!).

**Comment by kean** [comment]
If you believe there is an issue with `ImageProcessors.Resize`, I would appreciate if you could provide an input image and the parameters that you used.

**Comment by kean** [comment]
I deprecated `crop` parameter https://github.com/kean/Nuke/releases/tag/9.2.2, thanks for reporting this.

**Comment by Prince2k3** [comment]
I'll add the url I was using to test this.

```swift

WebImage(request: ImageRequest(url: imageURL, processors: [
                                ImageProcessors.Resize(
                                    size: CGSize(width: 375, height: 260),
                                    crop: true,
                                    upscale: true
                                )
                            ]
                        )
                    )
```

the image url: https://media.prod.hop.life/477c274e0fbbd2c36e1f88bfd40ce383.jpg

Expected Output: An image at size of 375x260 

<img width="652" alt="Screen Shot 2020-12-26 at 4 04 40 PM" src="https://user-images.githubusercontent.com/2805285/103159866-2071e880-4794-11eb-9bd4-162d1d2abddc.png">


Actual Output: Image is greater than the specified size. It does resize but not to the specified size.

<img width="550" alt="Screen Shot 2020-12-26 at 4 04 24 PM" src="https://user-images.githubusercontent.com/2805285/103159864-1b149e00-4794-11eb-9d12-4ab2939c953a.png">

**Comment by Prince2k3** [comment]
I want to say this library is by far the best image library out there. I commend the work you put into this for SwiftUI. The integration with your library Nuke is simple and clean. It is by far the cleanest well maintained library against the rest that I've seen! @kean

**Comment by kean** [comment]
Yeah, you are right, there is an issue which has to do with image orientation.

On a surface level everything seems fine:

```
(lldb) po input.cgImage
▿ Optional<CGImageRef>
  - some : <CGImage 0x7fd58a14f4c0> (IP)
	<<CGColorSpace 0x7fd58a14eba0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 1920, height = 1080, bpc = 8, bpp = 32, row bytes = 7680 
		kCGImageAlphaNoneSkipLast | 0 (default byte order)  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes

(lldb) po output.cgImage
▿ Optional<CGImageRef>
  - some : <CGImage 0x7fd58a1521c0> (DP)
	<<CGColorSpace 0x7fd58a14eba0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1)>
		width = 1125, height = 780, bpc = 8, bpp = 32, row bytes = 4512 
		kCGImageAlphaNoneSkipLast | 0 (default byte order)  | kCGImagePixelFormatPacked 
		is mask? No, has masking color? No, has soft mask? No, has matte? No, should interpolate? Yes

(lldb) po Screen.scale
3.0
```

The problem has to do with image orientation.

```swift
(lldb) p input.imageOrientation
(UIImage.Orientation) $R32 = right
(lldb) p output.imageOrientation
(UIImage.Orientation) $R34 = right
```

So the width visually becomes height. I'm surprised I missed it since I already worked with image orientation and CGGraphics before. Nuke needs to take image orientation into account when making these calculations.

**Comment by Prince2k3** [comment]
ah that would make sense. I wouldn't thought that either. Ugh ...images taken from camera seem to have weird outputs sometimes.

**Comment by kean** [comment]
Image orientation support added in [Nuke 9.2.4](https://github.com/kean/Nuke/releases/tag/9.2.4)
